In [1]:
# Numpy Assignment!!

# 1. What is a Python library? Why ^o we use Python libraries?


A Python library is a collection of pre-written Python code that provides functionalities to perform specific tasks. These libraries contain reusable modules and functions that help developers save time and effort by leveraging existing code rather than writing everything from scratch.

We use Python libraries for several reasons:

Efficiency: Libraries provide pre-written code for common tasks, which saves time and effort for developers. Instead of reinventing the wheel, developers can focus on solving the specific problem at hand.

Functionality: Python libraries offer a wide range of functionalities, from basic operations like mathematical calculations to complex tasks like machine learning or web development.

Community Support: Python has a vibrant community of developers who contribute to various libraries. This means that there are often multiple libraries available for a given task, allowing developers to choose the one that best fits their needs.

Reliability: Established Python libraries are typically well-tested and maintained, which increases their reliability and reduces the likelihood of errors.

Compatibility: Python libraries are designed to work seamlessly with other Python code, making it easy to integrate them into existing projects.

Overall, Python libraries are essential tools for developers that enable them to build robust and feature-rich applications more efficiently.

# 2. What is the difference between Numpy array and List?




NumPy arrays and Python lists are both used to store collections of data, but they have some key differences:

Data Types:

In a Python list, you can store heterogeneous data types (e.g., integers, floats, strings) together.
NumPy arrays are homogeneous; they can only store elements of the same data type. This allows for more efficient storage and computation, as NumPy arrays use contiguous blocks of memory.
Performance:

NumPy arrays typically offer better performance for numerical computations compared to Python lists. This is because NumPy arrays are implemented in C and are optimized for operations such as element-wise arithmetic, matrix operations, and linear algebra.
Python lists are more flexible but are slower for numerical computations, especially when dealing with large datasets.
Size and Memory Efficiency:

NumPy arrays require less memory compared to Python lists, especially when dealing with large datasets, due to their homogeneous nature and efficient memory allocation.
Python lists are more memory-inefficient because they store additional information such as type information and references to objects.
Functionality:

NumPy arrays offer a wide range of mathematical functions and operations optimized for numerical computations, such as element-wise arithmetic, statistical operations, and linear algebra.
Python lists offer more flexibility and a wider range of built-in methods for general-purpose manipulation, such as adding or removing elements, slicing, and concatenation.
In summary, NumPy arrays are optimized for numerical computations and offer better performance and memory efficiency compared to Python lists, while Python lists are more flexible and versatile but are generally slower for numerical operations.


In [2]:
# 3. Find the shape, size and dimension of the following array?

"""[[1, 2, 3, 4]
    [5, 6, 7, 8],
    [9, 10, 11, 12]] """

# To find the shape, size, and dimension of the given array, we can use NumPy, assuming the array is represented using NumPy arrays. Here's how you can do it:



import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Find shape
shape = arr.shape

# Find size
size = arr.size

# Find dimension
dimension = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)



Shape: (3, 4)
Size: 12
Dimension: 2


Explanation:

Shape: The shape of the array is (3, 4), meaning it has 3 rows and 4 columns.
Size: The size of the array is 12, which is the total number of elements in the array.
Dimension: The dimension of the array is 2, indicating it is a 2-dimensional array.





In [3]:
# 4. Write python code to access the first row of the following array?

"""[[1, 2, 3, 4]   
   [5, 6, 7, 8],
   [9, 10, 11, 12]] """

# To access the first row of the given array, you can use array indexing. In Python, array indexing starts from 0. Here's how ywe can access the first row:


import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row
first_row = arr[0]

print("First Row:", first_row)


First Row: [1 2 3 4]


Explanation:-

Import NumPy: We import the NumPy library, which is a popular Python library used for numerical computing. NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

Define the array: We define the array as a NumPy array. In this case, it's a 2-dimensional array with 3 rows and 4 columns. Each row represents a list of numbers, and the entire structure forms a grid-like arrangement.

Access the first row: To access the first row of the array, we use array indexing. In Python, array indexing starts from 0, so the first row has an index of 0. By using arr[0], we retrieve the first row of the array arr.

Print the first row: Finally, we print the first row to see the result. The output displays the elements of the first row enclosed within square brackets. Each number corresponds to an element in the first row of the array arr.

By following these steps, we are able to access and display the first row of the given array. This method allows us to selectively access specific rows or columns of a NumPy array, enabling efficient manipulation and analysis of data stored in arrays.

In [4]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?

"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]]"""   


# To access the element at the third row and fourth column from the given NumPy array, you can use array indexing. Remember that indexing in Python starts from 0, so the third row and fourth column will have indices 2 and 3 respectively. 


import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]

print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


Explanation:-

Import NumPy: NumPy is a Python library used for numerical computing. We import it using the import statement and assign it the alias np, which is a common convention.

Define the array: We define a 2-dimensional NumPy array using the np.array() function. This array is structured with 3 rows and 4 columns, as specified in the question.

Accessing elements: To access a specific element in a NumPy array, we use array indexing. The element at the third row and fourth column can be accessed using the syntax array[row_index, column_index]. Since indexing in Python starts from 0, the third row has an index of 2 and the fourth column has an index of 3.

Printing the element: After accessing the desired element, we print it to the console using the print() function.

Output: The output displays the value of the element at the specified position in the array. In this case, the output shows the value 12, which is the element at the third row and fourth column of the array.

By following these steps, we can effectively access and retrieve specific elements from a NumPy array, enabling us to manipulate and analyze data stored in arrays.

In [5]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?


"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]] """   


# To extract all odd-indexed elements from the given NumPy array, you can use array slicing. Remember that indexing in Python starts from 0, so odd-indexed elements will have indices 1, 3, 5, and so on. 


import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


Explanation:-

Import NumPy: NumPy is a Python library used for numerical computing. We import it using the import statement and assign it the alias np, which is a common convention.

Define the array: We define a 2-dimensional NumPy array using the np.array() function. This array is structured with 3 rows and 4 columns, as specified in the question.

Extracting odd-indexed elements: To extract all odd-indexed elements from the array, we use array slicing. Array slicing allows us to extract portions of arrays based on specified indices or ranges. In this case, we want to extract elements from all rows but only from columns with odd indices.

Array slicing syntax: The slicing syntax [:, 1::2] indicates that we want to include all rows (: before the comma) and select columns starting from index 1 (1::2) with a step size of 2. This means we start from the second column (index 1) and include every other column, effectively selecting only the odd-indexed columns.

Printing the extracted elements: After extracting the odd-indexed elements, we print them to the console using the print() function.

Output: The output displays the elements extracted from each row of the array. Each row in the output corresponds to a row from the original array, but only odd-indexed elements are retained. This allows us to effectively filter and extract specific elements from the array based on their indices.

By following these steps, we are able to extract all odd-indexed elements from the given NumPy array, enabling us to manipulate and analyze data stored in arrays effectively.






In [6]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

# To generate a random 3x3 matrix with values between 0 and 1, you can use the numpy.random.rand() function from the NumPy library. This function generates an array of random numbers from a uniform distribution over the interval [0, 1). 


import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)


Random 3x3 matrix with values between 0 and 1:
[[0.66911709 0.55386114 0.90166129]
 [0.72439552 0.46417954 0.89044053]
 [0.86922291 0.07975319 0.95120599]]


Explanation:

np.random.rand(3, 3) generates a 3x3 array of random numbers between 0 and 1. The function rand() generates samples from a uniform distribution over the interval [0, 1).
The generated random matrix is stored in the variable random_matrix.
Finally, we print the random matrix to the console using the print() function.





# 8. Describe the difference between np.random.rand and np.random.randn?


The difference between np.random.rand and np.random.randn lies in the distribution of the generated random numbers:

np.random.rand:

This function generates random numbers from a uniform distribution over the interval [0, 1).
When you call np.random.rand, it returns random numbers from a uniform distribution, meaning that each value has an equal probability of being selected from the range [0, 1).
The syntax for generating random numbers using np.random.rand is np.random.rand(d0, d1, ..., dn) where d0, d1, ..., dn specify the dimensions of the output array.
Example: np.random.rand(3, 3) generates a 3x3 array of random numbers between 0 and 1.
np.random.randn:

This function generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
When you call np.random.randn, it returns random numbers from a normal distribution centered around 0 with a standard deviation of 1.
The syntax for generating random numbers using np.random.randn is similar to np.random.rand: np.random.randn(d0, d1, ..., dn) where d0, d1, ..., dn specify the dimensions of the output array.
Example: np.random.randn(3, 3) generates a 3x3 array of random numbers from a standard normal distribution.
In summary:

np.random.rand generates random numbers from a uniform distribution over the interval [0, 1).
np.random.randn generates random numbers from a standard normal distribution with mean=0 and standard deviation=1.


In [7]:
# 9. Write code to increase the dimension of the following array?

"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]] """   


# To increase the dimension of the given array, you can use NumPy's np.expand_dims() function. This function adds a new axis at the specified position in the array, effectively increasing its dimension. 

import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase the dimension of the array
expanded_arr = np.expand_dims(arr, axis=0)

print("Original array shape:", arr.shape)
print("Expanded array shape:", expanded_arr.shape)
print("Expanded array:")
print(expanded_arr)


Original array shape: (3, 4)
Expanded array shape: (1, 3, 4)
Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Explanation:

np.expand_dims(arr, axis=0) adds a new axis at position 0, effectively increasing the dimension of the array by 1.
The original array arr has a shape of (3, 4), meaning it has 3 rows and 4 columns.
The expanded array expanded_arr has a shape of (1, 3, 4), indicating that it has been expanded to have 1 dimension along the first axis, while maintaining the original dimensions along the remaining axes.
The expanded array now has an additional outermost dimension, making it a 3-dimensional array.





In [8]:
# 10. How to transpose the following array in NumPy?

"""[[1, 2, 3, 4]
   [5, 6, 7, 8],
   [9, 10, 11, 12]] """   


# In NumPy, you can transpose an array using the .T attribute or the np.transpose() function


import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using .T attribute
transposed_arr = arr.T

# Alternatively, transpose the array using np.transpose() function
# transposed_arr = np.transpose(arr)

print("Original array:")
print(arr)
print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Explanation:-

Transposition of Arrays: Transposing an array involves flipping the array along its diagonal, effectively swapping its rows and columns.

Using NumPy Functions: NumPy provides convenient functions for array manipulation, including transposition. Two common methods to transpose an array in NumPy are:

Using .T Attribute: NumPy arrays have a .T attribute, which returns the transpose of the array. This is achieved by flipping the rows and columns of the array.

Using np.transpose() Function: Alternatively, you can use the np.transpose() function to transpose an array. This function takes the array as input and returns its transpose.

Result: After transposing the array, the dimensions are swapped. For example, a 3x4 array becomes a 4x3 array after transposition.

Output: The transposed array contains the same elements as the original array, but their positions are rearranged. Each element's position in the transposed array corresponds to the reverse position of its corresponding element in the original array.

By transposing arrays, we can efficiently manipulate and analyze data, especially in mathematical and scientific computations where rearranging dimensions can be beneficial.







In [9]:
# 11. Consider the following matrix:

"""11. Consider the following matrix:

       Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
       Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
       Perform the following operation using Python1
       ,+ I(dex wiLe multiplicatio'
       ]+ Matix multiplicatio'
       + Add both the maticK
       -+ Subtact matix B om 
       + Diide Matix B by A        """



# To perform the given operations on matrices A2 and B2 using Python and NumPy, we will follow these steps:

"""Define the matrices A2 and B2.
Perform element-wise addition (+) of the matrices A2 and B2.
Perform element-wise subtraction (-) of the matrix B2 from A2.
Perform matrix multiplication (*) of the matrices A2 and B2.
Perform matrix division (/) of matrix B2 by A2."""



import numpy as np

# Define Matrix A2
A2 = np.array([[1,  2,  3,  4],
               [5,  6,  7,  8],
               [9, 10, 11, 12]])

# Define Matrix B2 (same as A2)
B2 = np.array([[1,  2,  3,  4],
               [5,  6,  7,  8],
               [9, 10, 11, 12]])

# Perform element-wise addition
addition_result = A2 + B2
print("Element-wise addition of A2 and B2:")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = A2 - B2
print("\nElement-wise subtraction of B2 from A2:")
print(subtraction_result)

# Perform matrix multiplication
matrix_multiplication_result = np.dot(A2, B2.T)
print("\nMatrix multiplication of A2 and B2 (transposed):")
print(matrix_multiplication_result)

# Perform matrix division
matrix_division_result = B2 / A2
print("\nMatrix division of B2 by A2:")
print(matrix_division_result)



Element-wise addition of A2 and B2:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Element-wise subtraction of B2 from A2:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix multiplication of A2 and B2 (transposed):
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix division of B2 by A2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Explanation:-

Element-wise Addition (+):

Element-wise addition involves adding corresponding elements of two matrices.
For example, to add matrices A2 and B2, you simply add each element of A2 to the corresponding element of B2.
The resulting matrix will have the same dimensions as the original matrices, and each element in the result will be the sum of the corresponding elements from A2 and B2.
Element-wise Subtraction (-):

Element-wise subtraction involves subtracting corresponding elements of two matrices.
For example, to subtract matrix B2 from matrix A2, you subtract each element of B2 from the corresponding element of A2.
The resulting matrix will have the same dimensions as the original matrices, and each element in the result will be the difference between the corresponding elements of A2 and B2.
Matrix Multiplication (*):

Matrix multiplication, also known as the dot product, involves multiplying corresponding elements of rows and columns of two matrices and summing the results.
To perform matrix multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.
The resulting matrix will have dimensions equal to the number of rows of the first matrix and the number of columns of the second matrix.
Matrix Division (/):

Matrix division involves dividing corresponding elements of two matrices.
For example, to divide matrix B2 by matrix A2, you divide each element of B2 by the corresponding element of A2.
Note that division by zero is not allowed, so you need to ensure that A2 does not contain zero elements where division is performed.
The resulting matrix will have the same dimensions as the original matrices, and each element in the result will be the quotient of the corresponding elements of B2 and A2.
These operations are fundamental in matrix algebra and are often used in various mathematical and scientific applications for data manipulation and analysis.


In [10]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

# In NumPy, you can use the byteswap() function to swap the byte order of an array. This function creates a view of the array with the byte order swapped


import numpy as np

# Create an array with a specified byte order
arr = np.array([1, 256], dtype=np.int16)

# Swap the byte order of the array
swapped_arr = arr.byteswap()

print("Original array:")
print(arr)
print("\nArray with byte order swapped:")
print(swapped_arr)


Original array:
[  1 256]

Array with byte order swapped:
[256   1]


Explanation:-


Certainly! Here's the detailed explanation in theory:

In NumPy, the byteswap() function is used to swap the byte order of the elements in an array. This operation can be useful when working with data that is stored in a different byte order than the one expected by your system. Here's how the function works:

Byte Order in NumPy:

NumPy arrays have a specific byte order, which determines how the elements are stored in memory.
The byte order can be either little-endian (least significant byte stored first) or big-endian (most significant byte stored first).
By default, NumPy arrays have the same byte order as the system they are created on.
Swapping Byte Order:

The byteswap() function in NumPy creates a view of the array with the byte order swapped.
This means that the least significant byte becomes the most significant byte, and vice versa, for each element in the array.
The function operates element-wise on the array, swapping the byte order of each individual element.
Usage:

To use the byteswap() function, you simply call it on the array you want to modify.
It returns a new array with the byte order swapped, while the original array remains unchanged.
You can also specify the byte order explicitly using the byteorder parameter, which allows you to swap the byte order to a specific format.
Example:

For example, if you have an array [1, 256] of data type int16, where each element is represented by 2 bytes:
In little-endian byte order, the bytes for 1 are [0x01, 0x00] and for 256 are [0x00, 0x01].
In big-endian byte order, the bytes for 1 are [0x00, 0x01] and for 256 are [0x01, 0x00].
After applying byteswap(), the byte order of each element is swapped, resulting in [256, 1].
Conclusion:

The byteswap() function in NumPy provides a convenient way to handle data with different byte orders, ensuring compatibility and consistency when working with arrays across different systems.





# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. 


Matrix Inversion:

In linear algebra, the inverse of a square matrix A, denoted as A^(-1), is a matrix that, when multiplied by A, results in the identity matrix. In other words, A * A^(-1) = I, where I is the identity matrix.
Finding the inverse of a matrix is crucial in various mathematical computations and systems of linear equations.
Solving Linear Systems:

The inverse of a matrix can be used to solve systems of linear equations of the form Ax = b, where A is the coefficient matrix, x is the vector of unknowns, and b is the vector of constants.
By multiplying both sides of the equation by the inverse of A, you can solve for x: x = A^(-1) * b.
Numerical Stability:

The np.linalg.inv function provides a numerically stable way to compute the inverse of a matrix.
Inverting matrices directly can be numerically unstable, especially if the matrix is ill-conditioned or close to singular. The np.linalg.inv function handles these cases efficiently.
Applications:

Matrix inversion is used in various applications such as least squares regression, optimization problems, solving linear systems in physics and engineering, and inverting matrices in computer graphics and image processing algorithms.
Caution:

It's important to note that not all matrices have an inverse. A matrix must be square and non-singular (i.e., its determinant must be non-zero) to have an inverse.
Additionally, even if a matrix has an inverse, numerical errors can occur when computing the inverse, especially for matrices that are close to singular.


In [11]:
# 14. What does the np.reshape function do, and how is it used?

# The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while maintaining the same data.


""" Changing Array Shape:

The np.reshape function changes the shape of an array by rearranging its elements into a new shape.
The new shape specified must be compatible with the number of elements in the original array. In other words, the total number of elements in the original array must be equal to the total number of elements in the new shape.
Syntax:

The syntax for np.reshape is np.reshape(array, new_shape).
array is the original array whose shape you want to change.
new_shape is a tuple specifying the new shape of the array.
Usage:

You can use np.reshape to convert a 1-dimensional array into a multi-dimensional array or vice versa, or to change the shape of a multi-dimensional array. """



import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 2 rows and 3 columns
arr2d = np.reshape(arr1d, (2, 3))


""" Order Argument:

The np.reshape function also has an optional order argument, which specifies the order in which the elements are read from and written to memory. It can be 'C' (row-major) or 'F' (column-major). By default, it uses 'C' order. """

# Reshape the array with 'F' order
arr2d_f_order = np.reshape(arr1d, (2, 3), order='F')


""" View vs Copy:

It's important to note that np.reshape returns a view of the original array if possible, rather than creating a new array. This means that the data is not copied, and modifications to the reshaped array will affect the original array as well, and vice versa, as long as they share the same memory. """



" View vs Copy:\n\nIt's important to note that np.reshape returns a view of the original array if possible, rather than creating a new array. This means that the data is not copied, and modifications to the reshaped array will affect the original array as well, and vice versa, as long as they share the same memory. "

In [12]:
# 15. What is broadcasting in Numpy?



import numpy as np

# Create two arrays with different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Perform element-wise addition using broadcasting
result = arr1 + arr2

# The array arr2 is broadcasted to match the shape of arr1


Explanation:-

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined and operated upon together, even if their shapes do not match exactly. It enables NumPy to perform element-wise operations on arrays with different shapes, without the need for explicit loops. Here's an explanation of broadcasting:

Shapes Compatibility:

Broadcasting occurs when NumPy automatically adjusts the shapes of arrays to make them compatible for element-wise operations.
Two arrays are compatible for broadcasting if their shapes are compatible or if one of them can be broadcasted to match the shape of the other.
Broadcasting Rules:

Broadcasting follows a set of rules to determine how arrays with different shapes are aligned and combined:
Rule 1: If the arrays have a different number of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.
Rule 2: If the shape of any dimension in either array does not match, and one of them is 1, then the array with size 1 is stretched to match the shape of the other array along that dimension.
Rule 3: If the shapes of the arrays do not match and neither array has size 1 along any dimension, then broadcasting is not possible, and NumPy raises a ValueError.